# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [ ]:
'''
list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

list()的結果是：list of np.array of np.int；
而tolist()的結果是：list of list of int
'''

'\nYour Code\n'

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [4]:
import numpy as np

a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2))

print(a)
# [4 5 7 0 7 6]
# 一維陣列 shape(6,)
print(b)
# [[2 1 8 3]
#  [7 1 0 4]
#  [9 9 4 7]]
# 二維陣列 shape(3, 4)
print(c)
# [[[2 6]
#   [9 9]
#   [3 7]]

#  [[1 3]
#   [4 2]
#   [8 4]]]
# 三維陣列 shape(3, 2, 2)
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.data, len(a), type(a))
# 1 (6,) 6 int32 4 <memory at 0x000001BF3975B340> 6 <class 'numpy.ndarray'>
# 維度, 形狀(大小), 元素個數, 資料型態(整數), 每個元素占用的空間, 記憶體位置, 第一個維度的元素個數(6,), 為 Numpy/ndarray這個 class 
print(b.ndim, b.shape, b.size, b.dtype, b.itemsize, b.data, len(b), type(b))
# 2 (3, 4) 12 int32 4 <memory at 0x000001BF39757AD0> 3 <class 'numpy.ndarray'>
# 維度, 形狀(大小), 元素個數, 資料型態(整數), 每個元素占用的空間, 記憶體位置, 第一個維度的元素個數(6,), 為 Numpy/ndarray這個 class 
print(c.ndim, c.shape, c.size, c.dtype, c.itemsize, c.data, len(c), type(c))
# (2, 3, 2) 12 int32 4 <memory at 0x000001BF39754A90> 2 <class 'numpy.ndarray'>
# 維度, 形狀(大小), 元素個數, 資料型態(整數), 每個元素占用的空間, 記憶體位置, 第一個維度的元素個數(6,), 為 Numpy/ndarray這個 class 


[7 3 1 6 5 5]
[[2 1 8 3]
 [9 8 2 6]
 [9 0 6 6]]
[[[9 2]
  [7 3]
  [1 9]]

 [[4 9]
  [8 7]
  [1 5]]]
1 (6,) 6 int32 4 <memory at 0x000001BF3975B340> 6 <class 'numpy.ndarray'>
2 (3, 4) 12 int32 4 <memory at 0x000001BF39757AD0> 3 <class 'numpy.ndarray'>
3 (2, 3, 2) 12 int32 4 <memory at 0x000001BF39754A90> 2 <class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [6]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[6, 9, 8, 2, 5, 3]
[6, 9, 8, 2, 5, 3]


In [9]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print([list(b[0]), list(b[1]), list(b[2])])


[[4, 0, 0, 3], [5, 7, 8, 2], [4, 1, 5, 6]]
[[4, 0, 0, 3], [5, 7, 8, 2], [4, 1, 5, 6]]


In [39]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
d = []
for k in range(2):
    e = []
    for i in range(3):
        e.append(list(c[k][i]))
    d.append(e)

print(d)
    

    
# print(list(c[0]))
# print(list(c[1]))

[[[5, 6], [7, 7], [0, 3]], [[2, 7], [0, 6], [1, 9]]]
[[[5, 6], [7, 7], [0, 3]], [[2, 7], [0, 6], [1, 9]]]
