作業目標<br>
熟悉陣列維度轉換，並且會擷取需要資料<br>
作業重點<br>
使用reshap須注意order用法<br>
where可以運用邏輯條件擷取資料

題目:<br>
1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")<br>
2.呈上題的array，找出被6除餘1的數的索引<br>

In [ ]:
# https://www.delftstack.com/zh-tw/tutorial/python-numpy/numpy-array-reshape-and-resize/

In [2]:
import numpy as np

In [31]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
print(array1)
print(array1.dtype)
array2 = np.reshape(array1, (5, 6))
array3 = np.reshape(array1, (5, 6), order="F")
# array2 = np.array((5, 6), list(array1), dtype=int, order="F")
print(array2)
print(array2.dtype)
print(array3)
print(array3.dtype)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
int32
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
int32
[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]
int32


In [ ]:
#2.呈上題的array，找出被6除餘1的數的索引


In [44]:
print(array3[1, 2])
for i in array3:
    print(i)
# print([array3[i, j] for k in array3 if array3[i, j] % 6 == 1])
# [array2]
# for array2[i, j] in array2:
#     if array2[i, j] % 6 == 1:
#         print(array2[i, j])

11
[ 0  5 10 15 20 25]
[ 1  6 11 16 21 26]
[ 2  7 12 17 22 27]
[ 3  8 13 18 23 28]
[ 4  9 14 19 24 29]


In [52]:
array4 = np.where(array3 % 6 == 1, array3, False )
array5 = np.where(array3 % 6 == 1)
print(array4)
print(array5)  # 輸出位置索引 array3[0, 5]/[1, 0]/[2, 1]/[3, 2]/[4, 3]

[[ 0  0  0  0  0 25]
 [ 1  0  0  0  0  0]
 [ 0  7  0  0  0  0]
 [ 0  0 13  0  0  0]
 [ 0  0  0 19  0  0]]
(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))


In [ ]:
# [xv if c else yv
#  for c, xv, yv in zip(condition, x, y)]

In [ ]:
# https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
# https://www.cnblogs.com/massquantity/p/8908859.html

In [ ]:
# python 資料分析 p.123

In [ ]:
# https://codertw.com/%E7%A8%8B%E5%BC%8F%E8%AA%9E%E8%A8%80/358538/
# 最後是看這個