# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [2]:
import numpy as np
print(np.zeros((2, 3)))
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


zeros: 依照指定的 shape 和 dtype 產生充滿1的陣列
empty：取得新記憶體建立新陣列，但不像 ones 或 zeros 一樣去填充值

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [30]:
# 記得先 Import 正確的套件
a = np.random.rand(2, 3)
# numpy.random.rand(d0, d1, …, dn) 的隨機樣本位於(0, 1)中。
print(a)

# sample = np.random.uniform(low=0.5, high=13.3, size=(2,3))
a1 = np.random.uniform(10, 20, (2, 3))
print(a1)


b = a.astype(np.int64)
b1 = a1.astype(np.int64)
print(b)
print(b1)

c = np.rint(a)
c1 = np.rint(a1)
print(c)
print(c1)




[[0.85311898 0.4369797  0.6360575 ]
 [0.45872273 0.74402038 0.84314535]]
[[11.21412881 15.4500156  10.86361289]
 [14.7717374  16.98891028 12.50373724]]
[[0 0 0]
 [0 0 0]]
[[11 15 10]
 [14 16 12]]
[[1. 0. 1.]
 [0. 1. 1.]]
[[11. 15. 11.]
 [15. 17. 13.]]


http://hk.uwenku.com/question/p-qvbblkwr-bdp.html


函數名	功能
numpy.ceil ( x, )	向正無窮取整，⌈ x ⌉ \lceil \bm x \rceil⌈ x ⌉
numpy.floor ( x, )	向負無窮取整，⌊ x ⌋ \lfloor \bm x \rfloor⌊ x ⌋
numpy.trunc/fix ( x, )	截取整數部分
numpy.rint ( x, )	四捨五入到最近整數
numpy.around ( x, )	四捨五入到給定的小數位
>>> a = np.array([-1.7, -1.1, -0.6, -0.2, 0.4, 0.6, 1.3, 2.0])
>>> a
array([-1.7, -1.1, -0.6, -0.2,  0.4,  0.6,  1.3,  2. ])
>>> np.ceil(a)
array([-1., -1., -0., -0.,  1.,  1.,  2.,  2.])
>>> np.floor(a)
array([-2., -2., -1., -1.,  0.,  0.,  1.,  2.])
>>> np.trunc(a)
array([-1., -1., -0., -0.,  0.,  0.,  1.,  2.])
>>> np.rint(a)
array([-2., -1., -1., -0.,  0.,  1.,  1.,  2.])
>>> np.around(a)
array([-2., -1., -1., -0.,  0.,  1.,  1.,  2.])
————————————————
版权声明：本文为CSDN博主「十里清风」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/sinat_34072381/article/details/84567523

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [35]:
m = 20
n = 40
a = np.random.rand(2, 3)
b = np.random.randint(m, n, (2,3))
print(a)
print(b)

[[0.01680871 0.666872   0.43752588]
 [0.97271431 0.15821242 0.34846636]]
[[38 30 28]
 [35 26 29]]


random.randint(low, hight) -> 返回一個位於[low,hight]之間的整數