# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [1]:
import numpy as np
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

print(a + a)  # [ 40  60  80 100]
print(a + b)  # [21 32 43 54]
print(a + c)  # [21 31 41 51]
print(a + d)  # [21 31 41 51]
print(a + e)  # 加不起來也不能 broadcast

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [2]:
# 記得先 Import 正確的套件

import numpy as np


In [5]:
A = np.ones(3)*1
B = np.ones(3)*2
print(A)
print(B)
print((A + B) * (-A / 2))

[1. 1. 1.]
[2. 2. 2.]
[-1.5 -1.5 -1.5]


In [19]:
sumAB = [i + j for (i, j) in zip(A, B)]
print(sumAB)

half_minusA = [i * -1 / 2 for i in A]
print(half_minusA)

multiply_them = [i * j for (i, j) in zip(sumAB, half_minusA)]
print(multiply_them)

[3.0, 3.0, 3.0]
[-0.5, -0.5, -0.5]
[-1.5, -1.5, -1.5]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [25]:
A = np.ones((1,6))
B = np.ones((6,1))

print(A)
print(B)

[[1. 1. 1. 1. 1. 1.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [28]:
C = np.dot(A, B)
D = np.outer(A, B)
# E = np.cross(A, B)
print(C)
print(D)
# print(E)

[[6.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [24]:
def dot(v, w):
    if len(v) == len(w):
        return sum(v_i * w_i for v_i, w_i in zip(v, w))
print(dot(A, B))



6.0


numpy.outer(a, b, out=None):計算兩個向量的外積。已知兩個輸入向量為a = [a0, a1, ..., aM]和b = [b0, b1, ..., bN]，則輸出為：

[[a0*b0  a0*b1 ... a0*bN ]
 [a1*b0    .
 [ ...          .
 [aM*b0            aM*bN ]]
————————————————
版权声明：本文为CSDN博主「QLMX」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/u011599639/article/details/77926402

>>> a = np.array([[1, 2], [1, 1]])
array([[1, 2],
       [1, 1]])
>>> b = np.array([[2, 3], [1, 3]])
array([[2, 3],
       [1, 3]])
>>> np.outer(a, b)
array([[2, 3, 1, 3],
       [4, 6, 2, 6],
       [2, 3, 1, 3],
       [2, 3, 1, 3]])
————————————————
版权声明：本文为CSDN博主「QLMX」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/u011599639/article/details/77926402

<!-- 
# (a1, b1, c1)X(a2, b2, c2) = (b1c2-c1b2, c1a2-a1c2, a1b2-b1a2)
# a1 b1 c1 a1 b1 c1
#      X  X  X
# a2 b2 c2 a2 b2 c2  -->

In [ ]:
# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```




### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


A = np.ones(3)*1
B = np.ones(3)*2

print((A + B) * (-A / 2))

### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


# 記得先 Import 正確的套件

import numpy as np


# 參考解答

A = np.ones((1,6))
B = np.ones((6,1))

print(A * B)
print(A @ B)



