# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [27]:
# 記得先 Import 正確的套件
import numpy as np

a = np.arange(1, 12)
print(a)

# smaller_than_two = (a > 2)
# bigger_than_right = (a < 8)
# print(smaller_than_two)
# print(bigger_than_right)

# between_two_eight = (smaller_than_two & bigger_than_right)
# print(between_two_eight)

# a[between_two_eight] = -1 * a[between_two_eight]
# print(a)

mask = (a > 2) & (a < 8)
print(mask)
a[mask] = -a[mask]
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11]
[False False  True  True  True  True  True False False False False]
[ 1  2 -3 -4 -5 -6 -7  8  9 10 11]


In [8]:
'''
Your Code
'''

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [31]:
A = np.random.rand(3, 6)
print(A, len(A))
mask = (A > 0.5)
print(A[mask], len(A[mask]))



'''
Your Code
'''

[[0.78684073 0.60881782 0.31484407 0.44750748 0.46090748 0.37273577]
 [0.68245495 0.90913917 0.25267449 0.80085596 0.81128376 0.77716459]
 [0.44232696 0.75085489 0.88552642 0.39863614 0.36108596 0.08771936]] 3
[0.78684073 0.60881782 0.68245495 0.90913917 0.80085596 0.81128376
 0.77716459 0.75085489 0.88552642] 9


'\nYour Code\n'

參考 python 資料分析 第二版 p.112