# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
'''
a 所在層級不同
'''

'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [22]:
# 記得先 Import 正確的套件
import numpy as np

a = np.random.random((5, 5))

print(a)

print(a.clip(0, 1))

[[0.65137814 0.39720258 0.78873014 0.31683612 0.56809865]
 [0.86912739 0.43617342 0.80214764 0.14376682 0.70426097]
 [0.70458131 0.21879211 0.92486763 0.44214076 0.90931596]
 [0.05980922 0.18428708 0.04735528 0.67488094 0.59462478]
 [0.53331016 0.04332406 0.56143308 0.32966845 0.50296683]]
[[0.65137814 0.39720258 0.78873014 0.31683612 0.56809865]
 [0.86912739 0.43617342 0.80214764 0.14376682 0.70426097]
 [0.70458131 0.21879211 0.92486763 0.44214076 0.90931596]
 [0.05980922 0.18428708 0.04735528 0.67488094 0.59462478]
 [0.53331016 0.04332406 0.56143308 0.32966845 0.50296683]]


In [28]:
b = np.random.random(10)
print(b)
b[b == b.max()] = -1

print(b)

'''
Your Code
'''

[0.76711663 0.70811536 0.79686718 0.55776083 0.96583653 0.1471569
 0.029647   0.59389349 0.1140657  0.95080985]
[ 0.76711663  0.70811536  0.79686718  0.55776083 -1.          0.1471569
  0.029647    0.59389349  0.1140657   0.95080985]


'\nYour Code\n'

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [ ]:
'''
Your Code
'''

[ 0.29347583  0.59303277 -1.          0.38043546  0.63265939  0.32472618
  0.11340241  0.68136955  0.89905432  0.74769935]
