作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [4]:
import numpy as np
from numpy.linalg import inv, qr

In [6]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
array2 = inv(array1)

print(array1)
print(array2)
print(array1.dot(array2))

[[10  8]
 [ 3  5]]
[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
[[1. 0.]
 [0. 1.]]


反矩陣 http://www1.pu.edu.tw/~hdchen/handout_bank/mm/97_2_la_handout_04.pdf

#2. 運用上列array計算特徵值、特徵向量?

https://kknews.cc/zh-tw/code/3qal9oy.html
https://www.youtube.com/watch?v=OGZX9CYYEic

In [7]:
w, v = np.linalg.eig(array1)
x, y = np.linalg.eig(array2)
print(w)
print(v)
print(x)
print(y)

[13.  2.]
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]
[0.07692308 0.5       ]
[[-0.93632918  0.70710678]
 [-0.35112344 -0.70710678]]


In [9]:
#3. 運用上列array計算SVD?
u, s, vh = np.linalg.svd(array1)
print(u)
print(s)
print(vh)

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]
[13.94721714  1.86417116]
[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]


In [ ]:
參考 python 資料分析 p129 線性代數
https://www.cupoy.com/qa/collection/00000174C4BC1B93000000016375706F795F70726572656C656173654355/0000017549469591000000226375706F795F72656C656173654349/00000177325EBD56000000526375706F795F72656C656173655155455354